MAR: lighthouse.c File Reference
lighthouse.c File Reference
Contains a visualization program which lets users visualize the steps of the MAR library.
#include "mar/camera/mar_camera.h"
#include "mar/vision/mar_mser.h"
#include "mar/vision/mar_sift.h"
#include "mar/augment/mar_augment.h"
#include <stdio.h>
#include <stdlib.h>
#include <GL/glut.h>
#include <sys/time.h>
#include <math.h>
Functions
int timeval_subtract (struct timeval *result, struct timeval *x, struct timeval *y)
A function which subtracts a timeval from another.
void draw_camera_frame (int texture)
Draws the camera frame.
void draw_ellipse (float x, float y, float a, float b, float angle)
Draws an ellipse.
void draw_selectable_region (float x, float y)
Draws a selectable region.
void draw_keypoint (float x, float y, float r, float angle)
Draws a SIFT keypoint.
void draw_mser_ellipses ()
Draw the MSER ellipses.
void draw_selectable_regions ()
Draw the Selectable Regions.
void draw_sift_keypoints ()
Draw the SIFT keypoints.
void draw_fps ()
Draw the current frames per second.
void draw_region_preview ()
Draw a preview of selectable regions.
void initialize_graphics (void)
Initiates graphics.
void update_and_display (void)
GLUT callback called to update the state and draw graphics.
void reshape (GLint width, GLint height)
GLUT callback called when the window is resized.
void mouse_button (int button, int state, int x, int y)
GLUT callback for when a mouse button is clicked.
void mouse_motion (int x, int y)
GLUT callback for when the mouse is moved.
void keyboard (unsigned char key, int x, int y)
GLUT callback for when a keyboard key is pressed.
void cleanup_lighthouse ()
Cleans up the program.
int main (int argc, char *argv[])
Entry point of the MAR visualization application.
Detailed Description
Contains a visualization program which lets users visualize the steps of the MAR library.
It is designed specifically for development, testing, and calibration.
Author:
Greg Eddington
Function Documentation
void cleanup_lighthouse ()
Cleans up the program.
References mar_augment_free(), MAR_ERROR_NONE, and mar_print_error().
Referenced by main().
void draw_camera_frame (int texture)
Draws the camera frame.
Parameters:
texture The ID of the OpenGL texture to use for drawing
References mar_augment_get_camera_frame_buffer().
Referenced by update_and_display().
void draw_ellipse (float x, float y, float a, float b, float angle)
Draws an ellipse.
Parameters:
x The center's X coordinate
y The center's Y coordinate
a The major axis
b The minor axis
angle The angle of rotation
Referenced by draw_mser_ellipses(), and draw_region_preview().
void draw_fps ()
Draw the current frames per second.
References timeval_subtract().
Referenced by update_and_display().
void draw_keypoint (float x, float y, float r, float angle)
Draws a SIFT keypoint.
Parameters:
x The center's X coordinate
y The center's Y coordinate
r The radius
angle The angle of rotation
Referenced by draw_sift_keypoints().
void draw_mser_ellipses ()
Draw the MSER ellipses.
References draw_ellipse(), mar_augment_get_regions(), MAR_ERROR_NONE, and mar_print_error().
Referenced by update_and_display().
void draw_region_preview ()
Draw a preview of selectable regions.
References draw_ellipse(), mar_augment_get_regions(), MAR_ERROR_NONE, and mar_print_error().
Referenced by update_and_display().
void draw_selectable_region (float x, float y)
Draws a selectable region.
Parameters:
x The center's X coordinate
y The center's Y coordinate
Referenced by draw_selectable_regions().
void draw_selectable_regions ()
Draw the Selectable Regions.
References draw_selectable_region(), mar_augment_get_regions(), MAR_ERROR_NONE, and mar_print_error().
Referenced by update_and_display().
void draw_sift_keypoints ()
Draw the SIFT keypoints.
References draw_keypoint(), mar_augment_get_keypoints(), MAR_ERROR_NONE, and mar_print_error().
Referenced by update_and_display().
void initialize_graphics (void)
Initiates graphics.
Referenced by main().
void keyboard (unsigned char key, int x, int y)
GLUT callback for when a keyboard key is pressed.
Parameters:
key The keyboard key pressed
x The mouse cursor X position
y The mouse cursor Y position
References mar_mser_get_delta(), mar_mser_get_max_area(), mar_mser_get_max_variation(), mar_mser_get_min_area(), mar_mser_get_min_diversity(), mar_mser_set_delta(), mar_mser_set_max_area(), mar_mser_set_max_variation(), mar_mser_set_min_area(), mar_mser_set_min_diversity(), mar_sift_free(), mar_sift_get_edge_threshold(), mar_sift_get_first_octave(), mar_sift_get_number_of_levels(), mar_sift_get_number_of_octaves(), mar_sift_get_peak_threshold(), mar_sift_new(), mar_sift_set_edge_threshold(), and mar_sift_set_peak_threshold().
Referenced by main().
int main (int argc, char * argv[])
Entry point of the MAR visualization application.
Parameters:
argc The number of arguments
argv The arguments
Returns:
EXIT_SUCCESS on success, EXIT_FAILURE otherwise
References cleanup_lighthouse(), initialize_graphics(), keyboard(), mar_augment_init(), mar_augment_start(), MAR_ERROR_NONE, mar_print_error(), mouse_button(), mouse_motion(), reshape(), and update_and_display().
void mouse_button (int button, int state, int x, int y)
GLUT callback for when a mouse button is clicked.
Parameters:
button The mouse button
state The mouse state
x The mouse cursor X position
y The mouse cursor Y position
Referenced by main().
void mouse_motion (int x, int y)
GLUT callback for when the mouse is moved.
Parameters:
x The mouse cursor X position
y The mouse cursor Y position
Referenced by main().
void reshape (GLint width, GLint height)
GLUT callback called when the window is resized.
Parameters:
width The new window width
height The new window height
Referenced by main().
int timeval_subtract (struct timeval * result, struct timeval * x, struct timeval * y)
A function which subtracts a timeval from another.
result = x - y
Parameters:
result Will be filled in with the difference
x The minuend
y The subtrahend
Returns:
1 if the result is negative, 0 if positive
Referenced by draw_fps().
void update_and_display (void)
GLUT callback called to update the state and draw graphics.
References draw_camera_frame(), draw_fps(), draw_mser_ellipses(), draw_region_preview(), draw_selectable_regions(), draw_sift_keypoints(), mar_augment_update(), MAR_ERROR_AGAIN, MAR_ERROR_INTERRUPTED, MAR_ERROR_NONE, and mar_print_error().
Referenced by main().