MAR: mar_sift.h File Reference
mar_sift.h File Reference
Contains code which is used for the scale invariant feature transform algorithm.
#include "../common/mar_error.h"
Data Structures
struct mar_sift_keypoint
A type to encompass a SIFT keypoint.
Defines
#define MAR_SIFT_DEFAULT_NUMBER_OF_KEYPOINTS 1024
The default number of SIFT keypoint buffer slots.
#define MAR_SIFT_MAX_OCTAVES -1
Used to specify the number of octaves of the SIFT filter being the maximum number of octaves possible.
#define MAR_SIFT_DEFAULT_NUMBER_OF_OCTAVES MAR_SIFT_MAX_OCTAVES
The default number of octaves used by the SIFT filter.
#define MAR_SIFT_DEFAULT_NUMBER_OF_LEVELS 3
The default number of levels of the SIFT filter.
#define MAR_SIFT_DEFAULT_FIRST_OCTAVE 0
The default first octave of the SIFT filter.
#define MAR_SIFT_DEFAULT_PEAK_THRESHOLD 0
The default value for the SIFT filter's peak threshold.
#define MAR_SIFT_DEFAULT_EDGE_THRESHOLD 100
The default value for the SIFT filter's edge threshold.
Functions
mar_error_code mar_sift_new (int width, int height, int number_of_octaves, int number_of_levels, int first_octave)
Creates a new SIFT filter.
void mar_sift_free ()
Frees the SIFT filter created by mar_sift_new.
mar_error_code mar_sift_get_keypoints (mar_sift_keypoint **keypoints, int *num_keypoints, unsigned char *frame_buffer)
Calculates and returns the SIFT keypoints for a camera frame.
mar_error_code mar_sift_set_peak_threshold (float threshold)
Sets the peak threshold value for SIFT filter.
mar_error_code mar_sift_set_edge_threshold (float threshold)
Sets the edge threshold value for SIFT filter.
mar_error_code mar_sift_get_peak_threshold (float *threshold)
Gets the peak threshold value for SIFT filter.
mar_error_code mar_sift_get_edge_threshold (float *threshold)
Gets the edge threshold value for SIFT filter.
mar_error_code mar_sift_get_first_octave (int *first_octave)
Gets the first octave used by the SIFT filter.
mar_error_code mar_sift_get_number_of_octaves (int *number_of_octaves)
Gets the number of octaves for SIFT filter.
mar_error_code mar_sift_get_number_of_levels (int *number_of_levels)
Gets the number of levels per octave for SIFT filter.
Detailed Description
Contains code which is used for the scale invariant feature transform algorithm.
Author:
Greg Eddington
Define Documentation
#define MAR_SIFT_DEFAULT_EDGE_THRESHOLD 100
The default value for the SIFT filter's edge threshold.
#define MAR_SIFT_DEFAULT_FIRST_OCTAVE 0
The default first octave of the SIFT filter.
#define MAR_SIFT_DEFAULT_NUMBER_OF_KEYPOINTS 1024
The default number of SIFT keypoint buffer slots.
Referenced by mar_sift_new().
#define MAR_SIFT_DEFAULT_NUMBER_OF_LEVELS 3
The default number of levels of the SIFT filter.
#define MAR_SIFT_DEFAULT_NUMBER_OF_OCTAVES MAR_SIFT_MAX_OCTAVES
The default number of octaves used by the SIFT filter.
#define MAR_SIFT_DEFAULT_PEAK_THRESHOLD 0
The default value for the SIFT filter's peak threshold.
#define MAR_SIFT_MAX_OCTAVES -1
Used to specify the number of octaves of the SIFT filter being the maximum number of octaves possible.
Function Documentation
void mar_sift_free ()
Frees the SIFT filter created by mar_sift_new.
References sift_filter, sift_image_buffer, and sift_keypoints.
Referenced by keyboard(), and mar_augment_free().
mar_error_code mar_sift_get_edge_threshold (float * threshold)
Gets the edge threshold value for SIFT filter.
May only be called if a SIFT filter has been created.
Parameters:
threshold Will be set to the edge threshold. This is the edge rejection threshold.
Returns:
MAR_ERROR_NONE on success, an error code on failure.
References sift_filter.
Referenced by keyboard().
mar_error_code mar_sift_get_first_octave (int * first_octave)
Gets the first octave used by the SIFT filter.
May only be called if a SIFT filter has been created.
Parameters:
first_octave Will be set to the first octave used by the SIFT filter.
Returns:
MAR_ERROR_NONE on success, an error code on failure.
References sift_filter.
Referenced by keyboard().
mar_error_code mar_sift_get_keypoints (mar_sift_keypoint ** keypoints, int * num_keypoints, unsigned char * frame_buffer)
Calculates and returns the SIFT keypoints for a camera frame.
Parameters:
keypoints A pointer to a pointer which will be modified to point to the array of keypoints.
num_keypoints The number of SIFT keypoints, and the size of the regions array
frame_buffer The camera's frame buffer
Returns:
MAR_ERROR_NONE on success, an error code on failure.
References mar_sift_keypoint::angle, MAR_SIFT_NBP, mar_sift_keypoint::radius, sift_filter, sift_image_buffer, sift_image_height, sift_image_width, sift_keypoints, sift_keypoints_size, mar_sift_keypoint::x, and mar_sift_keypoint::y.
Referenced by mar_augment_get_keypoints(), and mar_augment_update().
mar_error_code mar_sift_get_number_of_levels (int * number_of_levels)
Gets the number of levels per octave for SIFT filter.
May only be called if a SIFT filter has been created.
Parameters:
number_of_levels Will be set to the number of levels per octave of the SIFT filter.
Returns:
MAR_ERROR_NONE on success, an error code on failure.
References sift_filter.
Referenced by keyboard().
mar_error_code mar_sift_get_number_of_octaves (int * number_of_octaves)
Gets the number of octaves for SIFT filter.
May only be called if a SIFT filter has been created.
Parameters:
number_of_octaves Will be set to the number of octaves.
Returns:
MAR_ERROR_NONE on success, an error code on failure.
References sift_filter.
Referenced by keyboard().
mar_error_code mar_sift_get_peak_threshold (float * threshold)
Gets the peak threshold value for SIFT filter.
May only be called if a SIFT filter has been created.
Parameters:
threshold Will be set to the peak threshold. This is the minimum amount of contrast to accept a keypoint
Returns:
MAR_ERROR_NONE on success, an error code on failure.
References sift_filter.
Referenced by keyboard().
mar_error_code mar_sift_new (int width, int height, int number_of_octaves, int number_of_levels, int first_octave)
Creates a new SIFT filter.
Must be called before calling other MAR SIFT functions.
Parameters:
width The width of the camera frame
height The height of the camera frame
number_of_octaves The number of octaves used by the SIFT filter. Increasing the scale by an octave means doubling the size of the smoothing kernel, whose effect is roughly equivalent to halving the image resolution.
number_of_levels The number of levels used by the SIFT filter. Each octave is sampled at this given number of intermediate scales Increasing this number might in principle return more refined keypoints, but in practice can make their selection unstable due to noise.
first_octave The SIFT filter will iterate from first_octave to number_of_octaves
Returns:
MAR_ERROR_NONE on success, an error code on failure.
References MAR_SIFT_DEFAULT_NUMBER_OF_KEYPOINTS, sift_filter, sift_image_buffer, sift_image_height, sift_image_width, and sift_keypoints.
Referenced by keyboard(), and mar_augment_init().
mar_error_code mar_sift_set_edge_threshold (float threshold)
Sets the edge threshold value for SIFT filter.
May only be called if a SIFT filter has been created.
Parameters:
threshold The edge threshold. This is the edge rejection threshold.
Returns:
MAR_ERROR_NONE on success, an error code on failure.
References sift_filter.
Referenced by keyboard(), and mar_augment_init().
mar_error_code mar_sift_set_peak_threshold (float threshold)
Sets the peak threshold value for SIFT filter.
May only be called if a SIFT filter has been created.
Parameters:
threshold The peak threshold. This is the minimum amount of contrast to accept a keypoint
Returns:
MAR_ERROR_NONE on success, an error code on failure.
References sift_filter.
Referenced by keyboard(), and mar_augment_init().