MAR: mar_augment.c File Reference
mar_augment.c File Reference
Contains code which is used for augmentation.
#include "mar_augment.h"
#include "../common/mar_common.h"
#include <libconfig.h>
Data Structures
struct mar_augmentation
A MAR library augmentation.
Functions
MAR_PUBLIC mar_error_code mar_augment_init (char *filename)
Initializes augmentation using a configuration file.
MAR_PUBLIC mar_error_code mar_augment_init_from_defaults ()
Initializes augmentation using default settings.
MAR_PUBLIC mar_error_code mar_augment_start ()
Starts the augmentation camera.
MAR_PUBLIC mar_error_code mar_augment_stop ()
Stops the augmentation camera.
MAR_PUBLIC mar_error_code mar_augment_update ()
Updates an augmentation frame.
MAR_PUBLIC mar_error_code mar_augment_new_augmentation (mar_augmentation_id *id, mar_mser *region)
MAR_PUBLIC void mar_augment_free_augmentation (mar_augmentation_id id)
Frees resources for an augmentation.
MAR_PUBLIC mar_error_code mar_augment_get_regions (mar_mser **regions, int *num_regions)
Returns the maximally stable extremal regions for a camera frame.
MAR_PUBLIC mar_error_code mar_augment_get_keypoints (mar_sift_keypoint **keypoints, int *num_keypoints)
Returns the SIFT keypoints for a camera frame.
MAR_PUBLIC mar_camera_id mar_augment_get_camera ()
Gets the camera ID used for augmentation.
MAR_PUBLIC unsigned char * mar_augment_get_camera_frame_buffer ()
Returns the camera's frame buffer in an RGB24 format.
MAR_PUBLIC mar_error_code mar_augment_free ()
Frees the augmentation resources.
Variables
MAR_PRIVATE char mar_augment_initialized = 0
Whether or not the augmentation module has been initialized.
MAR_PRIVATE config_t mar_cfg
The configuration context used to load and store configuration values.
MAR_PRIVATE mar_camera_id camera_id = MAR_CAM_NO_CAMERA
The ID of the camera used for augmentation.
MAR_PRIVATE char mar_mser_calculated_this_frame = 0
Whether or not the MSER have been calculated.
MAR_PRIVATE mar_mser * mar_mser_regions
The MSER.
MAR_PRIVATE int mar_mser_num_regions
The number of MSER.
MAR_PRIVATE char mar_sift_calculated_this_frame = 0
Whether or not the SIFT keypoints have been calculated.
MAR_PRIVATE mar_sift_keypoint * mar_sift_keypoints
The SIFT keypoints.
MAR_PRIVATE int mar_sift_num_keypoints
The number of SIFT keypoints.
MAR_PRIVATE int mar_number_of_augmentations = 0
The number of augmentations.
MAR_PRIVATE char mar_augmentation_initialized [MAR_MAX_NUMBER_OF_AUGMENTATIONS]
Whether the augmentation exists.
MAR_PRIVATE mar_augmentation mar_augmentations [MAR_MAX_NUMBER_OF_AUGMENTATIONS]
Whether the augmentation exists.
Detailed Description
Contains code which is used for augmentation.
Author:
Greg Eddington
Function Documentation
MAR_PUBLIC mar_error_code mar_augment_free ()
Frees the augmentation resources.
Returns:
MAR_ERROR_NONE on success, an error code on failure.
References camera_id, mar_augment_initialized, mar_camera_free(), mar_cfg, mar_mser_free(), and mar_sift_free().
Referenced by cleanup_lighthouse().
MAR_PUBLIC void mar_augment_free_augmentation (mar_augmentation_id id)
Frees resources for an augmentation.
Parameters:
id The augmentation ID
References mar_augmentation_initialized, and mar_number_of_augmentations.
MAR_PUBLIC mar_camera_id mar_augment_get_camera ()
Gets the camera ID used for augmentation.
Returns:
The MAR library camera ID for the camera being used for augmentation
References camera_id.
MAR_PUBLIC unsigned char* mar_augment_get_camera_frame_buffer ()
Returns the camera's frame buffer in an RGB24 format.
The frame buffer is 3 * width * height in size.
Returns:
The camera frame buffer.
References camera_id, and mar_camera_get_frame_buffer().
Referenced by draw_camera_frame().
MAR_PUBLIC mar_error_code mar_augment_get_keypoints (mar_sift_keypoint ** keypoints, int * num_keypoints)
Returns the SIFT keypoints for a camera frame.
Parameters:
keypoints A pointer to a pointer which will be modified to point to the array of keypoints.
num_keypoints The number of SIFT keypoints, and the size of the regions array
Returns:
MAR_ERROR_NONE on success, an error code on failure.
References camera_id, mar_camera_get_frame_buffer(), mar_sift_calculated_this_frame, mar_sift_get_keypoints(), mar_sift_keypoints, and mar_sift_num_keypoints.
Referenced by draw_sift_keypoints().
MAR_PUBLIC mar_error_code mar_augment_get_regions (mar_mser ** regions, int * num_regions)
Returns the maximally stable extremal regions for a camera frame.
Parameters:
regions A pointer to a pointer which will be modified to point to the array of regions.
num_regions The number of MSER, and the size of the regions array
Returns:
MAR_ERROR_NONE on success, an error code on failure.
References camera_id, mar_camera_get_frame_buffer(), mar_mser_calculated_this_frame, mar_mser_get_regions(), mar_mser_num_regions, and mar_mser_regions.
Referenced by draw_mser_ellipses(), draw_region_preview(), and draw_selectable_regions().
MAR_PUBLIC mar_error_code mar_augment_init (char * filename)
Initializes augmentation using a configuration file.
Parameters:
filename The filename of the configuration file, NULL for default settings
Returns:
MAR_ERROR_NONE on success, an error code on failure.
Todo:
throw errors if initialized
Todo:
throw errors at uninitialized
References camera_id, mar_augment_initialized, mar_camera_free(), mar_camera_new(), mar_cfg, MAR_ERROR_NONE, mar_mser_free(), mar_mser_new(), mar_mser_set_delta(), mar_mser_set_max_area(), mar_mser_set_max_variation(), mar_mser_set_min_area(), mar_mser_set_min_diversity(), mar_sift_new(), mar_sift_set_edge_threshold(), and mar_sift_set_peak_threshold().
Referenced by main(), and mar_augment_init_from_defaults().
MAR_PUBLIC mar_error_code mar_augment_init_from_defaults ()
Initializes augmentation using default settings.
Returns:
MAR_ERROR_NONE on success, an error code on failure.
References mar_augment_init().
MAR_PUBLIC mar_error_code mar_augment_new_augmentation (mar_augmentation_id * id, mar_mser * region)
Todo:
document
Todo:
overflow error
References mar_augmentation_initialized, mar_augmentations, and mar_number_of_augmentations.
MAR_PUBLIC mar_error_code mar_augment_start ()
Starts the augmentation camera.
Returns:
MAR_ERROR_NONE on success, an error code on failure.
References camera_id, and mar_camera_start().
Referenced by main().
MAR_PUBLIC mar_error_code mar_augment_stop ()
Stops the augmentation camera.
Returns:
MAR_ERROR_NONE on success, an error code on failure.
References camera_id, and mar_camera_stop().
MAR_PUBLIC mar_error_code mar_augment_update ()
Updates an augmentation frame.
Returns:
MAR_ERROR_NONE on success, an error code on failure.
Todo:
augment reality
Todo:
check retval
References camera_id, mar_camera_get_frame_buffer(), mar_camera_update(), MAR_ERROR_NONE, mar_mser_calculated_this_frame, mar_number_of_augmentations, mar_sift_calculated_this_frame, mar_sift_get_keypoints(), mar_sift_keypoints, and mar_sift_num_keypoints.
Referenced by update_and_display().
Variable Documentation
MAR_PRIVATE mar_camera_id camera_id = MAR_CAM_NO_CAMERA
The ID of the camera used for augmentation.
Returns:
Referenced by mar_augment_free(), mar_augment_get_camera(), mar_augment_get_camera_frame_buffer(), mar_augment_get_keypoints(), mar_augment_get_regions(), mar_augment_init(), mar_augment_start(), mar_augment_stop(), and mar_augment_update().
MAR_PRIVATE char mar_augment_initialized = 0
Whether or not the augmentation module has been initialized.
Returns:
Referenced by mar_augment_free(), and mar_augment_init().
MAR_PRIVATE char mar_augmentation_initialized[MAR_MAX_NUMBER_OF_AUGMENTATIONS]
Whether the augmentation exists.
Referenced by mar_augment_free_augmentation(), and mar_augment_new_augmentation().
MAR_PRIVATE mar_augmentation mar_augmentations[MAR_MAX_NUMBER_OF_AUGMENTATIONS]
Whether the augmentation exists.
Referenced by mar_augment_new_augmentation().
MAR_PRIVATE config_t mar_cfg
The configuration context used to load and store configuration values.
Returns:
Referenced by mar_augment_free(), and mar_augment_init().
MAR_PRIVATE char mar_mser_calculated_this_frame = 0
Whether or not the MSER have been calculated.
Returns:
Referenced by mar_augment_get_regions(), and mar_augment_update().
MAR_PRIVATE int mar_mser_num_regions
The number of MSER.
Returns:
Referenced by mar_augment_get_regions().
MAR_PRIVATE mar_mser* mar_mser_regions
The MSER.
Returns:
Referenced by mar_augment_get_regions().
MAR_PRIVATE int mar_number_of_augmentations = 0
The number of augmentations.
Referenced by mar_augment_free_augmentation(), mar_augment_new_augmentation(), and mar_augment_update().
MAR_PRIVATE char mar_sift_calculated_this_frame = 0
Whether or not the SIFT keypoints have been calculated.
Returns:
Referenced by mar_augment_get_keypoints(), and mar_augment_update().
MAR_PRIVATE mar_sift_keypoint* mar_sift_keypoints
The SIFT keypoints.
Returns:
Referenced by mar_augment_get_keypoints(), and mar_augment_update().
MAR_PRIVATE int mar_sift_num_keypoints
The number of SIFT keypoints.
Returns:
Referenced by mar_augment_get_keypoints(), and mar_augment_update().