MAR: mar_sift.c File Reference
mar_sift.c File Reference
Contains code which is used for the scale invariant feature transform algorithm.
#include "../common/mar_common.h"
#include "mar_sift.h"
#include <sift.h>
Defines
#define MAR_SIFT_NBO 8
Number of SIFT bins per orientation.
#define MAR_SIFT_NBP 4
Number of SIFT bins per position.
Functions
MAR_PUBLIC mar_error_code mar_sift_new (int width, int height, int number_of_octaves, int number_of_levels, int first_octave)
Creates a new SIFT filter.
MAR_PUBLIC void mar_sift_free ()
Frees the SIFT filter created by mar_sift_new.
MAR_PUBLIC mar_error_code mar_sift_set_peak_threshold (float threshold)
Sets the peak threshold value for SIFT filter.
MAR_PUBLIC mar_error_code mar_sift_set_edge_threshold (float threshold)
Sets the edge threshold value for SIFT filter.
MAR_PUBLIC mar_error_code mar_sift_get_peak_threshold (float *threshold)
Gets the peak threshold value for SIFT filter.
MAR_PUBLIC mar_error_code mar_sift_get_edge_threshold (float *threshold)
Gets the edge threshold value for SIFT filter.
MAR_PUBLIC mar_error_code mar_sift_get_first_octave (int *first_octave)
Gets the first octave used by the SIFT filter.
MAR_PUBLIC mar_error_code mar_sift_get_number_of_octaves (int *number_of_octaves)
Gets the number of octaves for SIFT filter.
MAR_PUBLIC mar_error_code mar_sift_get_number_of_levels (int *number_of_levels)
Gets the number of levels per octave for SIFT filter.
MAR_PUBLIC mar_error_code mar_sift_get_keypoints (mar_sift_keypoint **keypoints, int *num_keypoints, unsigned char *frame_buffer)
Calculates and returns the SIFT keypoints for a camera frame.
Variables
MAR_PRIVATE VlSiftFilt * sift_filter = NULL
The SIFT filter.
MAR_PRIVATE float * sift_image_buffer
The image buffer to store a grayscale of the camera image for SIFT filtering.
MAR_PRIVATE int sift_image_width = 0
The image buffer width.
MAR_PRIVATE int sift_image_height = 0
The image buffer height.
MAR_PRIVATE mar_sift_keypoint * sift_keypoints = NULL
A buffer for holding SIFT keypoints found from filtering.
MAR_PRIVATE int sift_keypoints_size = MAR_SIFT_DEFAULT_NUMBER_OF_KEYPOINTS
The size of the SIFT keypoint buffer.
Detailed Description
Contains code which is used for the scale invariant feature transform algorithm.
Author:
Greg Eddington
Define Documentation
#define MAR_SIFT_NBO 8
Number of SIFT bins per orientation.
#define MAR_SIFT_NBP 4
Number of SIFT bins per position.
Referenced by mar_sift_get_keypoints().
Function Documentation
MAR_PUBLIC void mar_sift_free ()
Frees the SIFT filter created by mar_sift_new.
References sift_filter, sift_image_buffer, and sift_keypoints.
Referenced by keyboard(), and mar_augment_free().
MAR_PUBLIC mar_error_code mar_sift_get_edge_threshold (float * threshold)
Gets the edge threshold value for SIFT filter.
May only be called if a SIFT filter has been created.
Parameters:
threshold Will be set to the edge threshold. This is the edge rejection threshold.
Returns:
MAR_ERROR_NONE on success, an error code on failure.
References sift_filter.
Referenced by keyboard().
MAR_PUBLIC mar_error_code mar_sift_get_first_octave (int * first_octave)
Gets the first octave used by the SIFT filter.
May only be called if a SIFT filter has been created.
Parameters:
first_octave Will be set to the first octave used by the SIFT filter.
Returns:
MAR_ERROR_NONE on success, an error code on failure.
References sift_filter.
Referenced by keyboard().
MAR_PUBLIC mar_error_code mar_sift_get_keypoints (mar_sift_keypoint ** keypoints, int * num_keypoints, unsigned char * frame_buffer)
Calculates and returns the SIFT keypoints for a camera frame.
Parameters:
keypoints A pointer to a pointer which will be modified to point to the array of keypoints.
num_keypoints The number of SIFT keypoints, and the size of the regions array
frame_buffer The camera's frame buffer
Returns:
MAR_ERROR_NONE on success, an error code on failure.
References mar_sift_keypoint::angle, MAR_SIFT_NBP, mar_sift_keypoint::radius, sift_filter, sift_image_buffer, sift_image_height, sift_image_width, sift_keypoints, sift_keypoints_size, mar_sift_keypoint::x, and mar_sift_keypoint::y.
Referenced by mar_augment_get_keypoints(), and mar_augment_update().
MAR_PUBLIC mar_error_code mar_sift_get_number_of_levels (int * number_of_levels)
Gets the number of levels per octave for SIFT filter.
May only be called if a SIFT filter has been created.
Parameters:
number_of_levels Will be set to the number of levels per octave of the SIFT filter.
Returns:
MAR_ERROR_NONE on success, an error code on failure.
References sift_filter.
Referenced by keyboard().
MAR_PUBLIC mar_error_code mar_sift_get_number_of_octaves (int * number_of_octaves)
Gets the number of octaves for SIFT filter.
May only be called if a SIFT filter has been created.
Parameters:
number_of_octaves Will be set to the number of octaves.
Returns:
MAR_ERROR_NONE on success, an error code on failure.
References sift_filter.
Referenced by keyboard().
MAR_PUBLIC mar_error_code mar_sift_get_peak_threshold (float * threshold)
Gets the peak threshold value for SIFT filter.
May only be called if a SIFT filter has been created.
Parameters:
threshold Will be set to the peak threshold. This is the minimum amount of contrast to accept a keypoint
Returns:
MAR_ERROR_NONE on success, an error code on failure.
References sift_filter.
Referenced by keyboard().
MAR_PUBLIC mar_error_code mar_sift_new (int width, int height, int number_of_octaves, int number_of_levels, int first_octave)
Creates a new SIFT filter.
Must be called before calling other MAR SIFT functions.
Parameters:
width The width of the camera frame
height The height of the camera frame
number_of_octaves The number of octaves used by the SIFT filter. Increasing the scale by an octave means doubling the size of the smoothing kernel, whose effect is roughly equivalent to halving the image resolution.
number_of_levels The number of levels used by the SIFT filter. Each octave is sampled at this given number of intermediate scales Increasing this number might in principle return more refined keypoints, but in practice can make their selection unstable due to noise.
first_octave The SIFT filter will iterate from first_octave to number_of_octaves
Returns:
MAR_ERROR_NONE on success, an error code on failure.
References MAR_SIFT_DEFAULT_NUMBER_OF_KEYPOINTS, sift_filter, sift_image_buffer, sift_image_height, sift_image_width, and sift_keypoints.
Referenced by keyboard(), and mar_augment_init().
MAR_PUBLIC mar_error_code mar_sift_set_edge_threshold (float threshold)
Sets the edge threshold value for SIFT filter.
May only be called if a SIFT filter has been created.
Parameters:
threshold The edge threshold. This is the edge rejection threshold.
Returns:
MAR_ERROR_NONE on success, an error code on failure.
References sift_filter.
Referenced by keyboard(), and mar_augment_init().
MAR_PUBLIC mar_error_code mar_sift_set_peak_threshold (float threshold)
Sets the peak threshold value for SIFT filter.
May only be called if a SIFT filter has been created.
Parameters:
threshold The peak threshold. This is the minimum amount of contrast to accept a keypoint
Returns:
MAR_ERROR_NONE on success, an error code on failure.
References sift_filter.
Referenced by keyboard(), and mar_augment_init().
Variable Documentation
MAR_PRIVATE VlSiftFilt* sift_filter = NULL
The SIFT filter.
Returns:
Referenced by mar_sift_free(), mar_sift_get_edge_threshold(), mar_sift_get_first_octave(), mar_sift_get_keypoints(), mar_sift_get_number_of_levels(), mar_sift_get_number_of_octaves(), mar_sift_get_peak_threshold(), mar_sift_new(), mar_sift_set_edge_threshold(), and mar_sift_set_peak_threshold().
MAR_PRIVATE float* sift_image_buffer
The image buffer to store a grayscale of the camera image for SIFT filtering.
Returns:
Referenced by mar_sift_free(), mar_sift_get_keypoints(), and mar_sift_new().
MAR_PRIVATE int sift_image_height = 0
The image buffer height.
Returns:
Referenced by mar_sift_get_keypoints(), and mar_sift_new().
MAR_PRIVATE int sift_image_width = 0
The image buffer width.
Returns:
Referenced by mar_sift_get_keypoints(), and mar_sift_new().
MAR_PRIVATE mar_sift_keypoint* sift_keypoints = NULL
A buffer for holding SIFT keypoints found from filtering.
Returns:
Referenced by mar_sift_free(), mar_sift_get_keypoints(), and mar_sift_new().
MAR_PRIVATE int sift_keypoints_size = MAR_SIFT_DEFAULT_NUMBER_OF_KEYPOINTS
The size of the SIFT keypoint buffer.
Returns:
Referenced by mar_sift_get_keypoints().