MAR: mar_mser.h File Reference
mar_mser.h File Reference
Contains code which is used for the maximally stable extremal region algorithm.
#include "../common/mar_error.h"
Data Structures
struct mar_mser
A type to encompass maximally stable extremal region information.
Defines
#define MAR_MSER_DEFAULT_DELTA 6
The default value for the SIFT filter's delta.
#define MAR_MSER_DEFAULT_MIN_AREA 0.005
The default value for the SIFT filter's min area.
#define MAR_MSER_DEFAULT_MAX_AREA 0.4
The default value for the SIFT filter's max area.
#define MAR_MSER_DEFAULT_MIN_DIVERSITY 0.7
The default value for the SIFT filter's min diversity.
#define MAR_MSER_DEFAULT_MAX_VARIATION 0.2
The default value for the SIFT filter's max variation.
#define MAR_ELLIPSE_MEAN_X 0
The VLFeat libraries MSER ellipse's mean X index.
#define MAR_ELLIPSE_MEAN_Y 1
The VLFeat libraries MSER ellipse's mean Y index.
#define MAR_ELLIPSE_VARIANCE_X 2
The VLFeat libraries MSER ellipse's X variance index.
#define MAR_ELLIPSE_VARIANCE_Y 4
The VLFeat libraries MSER ellipse's Y variance index.
#define MAR_ELLIPSE_COVARIANCE 3
The VLFeat libraries MSER ellipse's covariance index.
#define MAR_MSER_DEFAULT_NUMBER_OF_REGIONS 256
The default number of MSER region buffer slots.
Functions
mar_error_code mar_mser_new (int width, int height)
Creates a new MSER filter.
void mar_mser_free ()
Frees the MSER filter created by mar_mser_new.
mar_error_code mar_mser_set_delta (float delta)
Sets the delta value for MSER filter.
mar_error_code mar_mser_set_min_area (float min_area)
Sets the minimum area for MSER filter regions.
mar_error_code mar_mser_set_max_area (float max_area)
Sets the maximum area for MSER filter regions.
mar_error_code mar_mser_set_max_variation (float max_variation)
Sets the max variation value for MSER filter.
mar_error_code mar_mser_set_min_diversity (float min_diversity)
Sets the minimum diversity value for MSER filter.
mar_error_code mar_mser_get_regions (mar_mser **regions, int *num_regions, unsigned char *frame_buffer)
Calculates and returns the maximally stable extremal regions for a camera frame.
mar_error_code mar_mser_get_delta (float *delta)
Gets the delta value for MSER filter.
mar_error_code mar_mser_get_min_area (float *min_area)
Gets the minimum area for MSER filter regions.
mar_error_code mar_mser_get_max_area (float *max_area)
Gets the maximum area for MSER filter regions.
mar_error_code mar_mser_get_max_variation (float *max_variation)
Gets the max variation value for MSER filter.
mar_error_code mar_mser_get_min_diversity (float *min_diversity)
Gets the minimum diversity value for MSER filter.
Detailed Description
Contains code which is used for the maximally stable extremal region algorithm.
Author:
Greg Eddington
Define Documentation
#define MAR_ELLIPSE_COVARIANCE 3
The VLFeat libraries MSER ellipse's covariance index.
#define MAR_ELLIPSE_MEAN_X 0
The VLFeat libraries MSER ellipse's mean X index.
#define MAR_ELLIPSE_MEAN_Y 1
The VLFeat libraries MSER ellipse's mean Y index.
#define MAR_ELLIPSE_VARIANCE_X 2
The VLFeat libraries MSER ellipse's X variance index.
#define MAR_ELLIPSE_VARIANCE_Y 4
The VLFeat libraries MSER ellipse's Y variance index.
#define MAR_MSER_DEFAULT_DELTA 6
The default value for the SIFT filter's delta.
#define MAR_MSER_DEFAULT_MAX_AREA 0.4
The default value for the SIFT filter's max area.
#define MAR_MSER_DEFAULT_MAX_VARIATION 0.2
The default value for the SIFT filter's max variation.
#define MAR_MSER_DEFAULT_MIN_AREA 0.005
The default value for the SIFT filter's min area.
#define MAR_MSER_DEFAULT_MIN_DIVERSITY 0.7
The default value for the SIFT filter's min diversity.
#define MAR_MSER_DEFAULT_NUMBER_OF_REGIONS 256
The default number of MSER region buffer slots.
Referenced by mar_mser_new().
Function Documentation
void mar_mser_free ()
Frees the MSER filter created by mar_mser_new.
References mser_filter, mser_image_buffer, and mser_regions.
Referenced by mar_augment_free(), and mar_augment_init().
mar_error_code mar_mser_get_delta (float * delta)
Gets the delta value for MSER filter.
May only be called if a MSER filter has been created.
Parameters:
delta Will be filled with the filter delta
Returns:
MAR_ERROR_NONE on success, an error code on failure.
References mser_filter.
Referenced by keyboard().
mar_error_code mar_mser_get_max_area (float * max_area)
Gets the maximum area for MSER filter regions.
May only be called if a MSER filter has been created.
Parameters:
max_area Will be filled with the maximum region area, normalized to [0-1], where one is the total area of the image.
Returns:
MAR_ERROR_NONE on success, an error code on failure.
References mser_filter.
Referenced by keyboard().
mar_error_code mar_mser_get_max_variation (float * max_variation)
Gets the max variation value for MSER filter.
May only be called if a MSER filter has been created.
Parameters:
max_variation Will be filled with the filter's max variation
Returns:
MAR_ERROR_NONE on success, an error code on failure.
References mser_filter.
Referenced by keyboard().
mar_error_code mar_mser_get_min_area (float * min_area)
Gets the minimum area for MSER filter regions.
May only be called if a MSER filter has been created.
Parameters:
min_area Will be filled with the minimum region area, normalized to [0-1], where one is the total area of the image.
Returns:
MAR_ERROR_NONE on success, an error code on failure.
References mser_filter.
Referenced by keyboard().
mar_error_code mar_mser_get_min_diversity (float * min_diversity)
Gets the minimum diversity value for MSER filter.
May only be called if a MSER filter has been created.
Parameters:
min_diversity The filter minimum diversity
Returns:
MAR_ERROR_NONE on success, an error code on failure.
References mser_filter.
Referenced by keyboard().
mar_error_code mar_mser_get_regions (mar_mser ** regions, int * num_regions, unsigned char * frame_buffer)
Calculates and returns the maximally stable extremal regions for a camera frame.
Parameters:
regions A pointer to a pointer which will be modified to point to the array of regions.
num_regions The number of MSER, and the size of the regions array
frame_buffer The camera's frame buffer
Returns:
MAR_ERROR_NONE on success, an error code on failure.
References mar_mser::ellipse_a, mar_mser::ellipse_angle, mar_mser::ellipse_b, mar_mser::ellipse_x, mar_mser::ellipse_y, mser_filter, mser_image_buffer, mser_image_height, mser_image_width, mser_regions, and mser_regions_size.
Referenced by mar_augment_get_regions().
mar_error_code mar_mser_new (int width, int height)
Creates a new MSER filter.
Must be called before calling other MAR MSER functions.
Parameters:
width The width of the camera frame
height The height of the camera frame
Returns:
MAR_ERROR_NONE on success, an error code on failure.
References MAR_MSER_DEFAULT_NUMBER_OF_REGIONS, mser_filter, mser_image_buffer, mser_image_height, mser_image_width, and mser_regions.
Referenced by mar_augment_init().
mar_error_code mar_mser_set_delta (float delta)
Sets the delta value for MSER filter.
May only be called if a MSER filter has been created.
Parameters:
delta The filter delta
Returns:
MAR_ERROR_NONE on success, an error code on failure.
References mser_filter.
Referenced by keyboard(), and mar_augment_init().
mar_error_code mar_mser_set_max_area (float max_area)
Sets the maximum area for MSER filter regions.
May only be called if a MSER filter has been created.
Parameters:
max_area The maximum region area, normalized to [0-1], where one is the total area of the image.
Returns:
MAR_ERROR_NONE on success, an error code on failure.
References mser_filter.
Referenced by keyboard(), and mar_augment_init().
mar_error_code mar_mser_set_max_variation (float max_variation)
Sets the max variation value for MSER filter.
May only be called if a MSER filter has been created.
Parameters:
max_variation The filter max variation
Returns:
MAR_ERROR_NONE on success, an error code on failure.
References mser_filter.
Referenced by keyboard(), and mar_augment_init().
mar_error_code mar_mser_set_min_area (float min_area)
Sets the minimum area for MSER filter regions.
May only be called if a MSER filter has been created.
Parameters:
min_area The minimum region area, normalized to [0-1], where one is the total area of the image.
Returns:
MAR_ERROR_NONE on success, an error code on failure.
References mser_filter.
Referenced by keyboard(), and mar_augment_init().
mar_error_code mar_mser_set_min_diversity (float min_diversity)
Sets the minimum diversity value for MSER filter.
May only be called if a MSER filter has been created.
Parameters:
min_diversity The filter minimum diversity
Returns:
MAR_ERROR_NONE on success, an error code on failure.
References mser_filter.
Referenced by keyboard(), and mar_augment_init().