MAR: mar_error.h File Reference
mar_error.h File Reference
Contains code which is used for error codes of the MAR library.
Defines
#define MAR_ERROR_NONE 0
no error has occurred
#define MAR_ERROR_MMAP_NOT_SUPPORTED 1
mmap not supported by the device
#define MAR_ERROR_BUFFER_REQUEST 2
error occurred when requesting device buffers
#define MAR_ERROR_INSUFFICIENT_DEVICE_MEMORY 3
device has insufficient memory
#define MAR_ERROR_QUERY_BUF 4
error querying buffer
#define MAR_ERROR_MMAP 5
error during mmap
#define MAR_ERROR_MUNMAP 6
error during munmap
#define MAR_ERROR_MALLOC 7
error during malloc
#define MAR_ERROR_DEVICE_NOT_FOUND 8
device was not found
#define MAR_ERROR_NOT_CHARACTER_DEVICE 9
device was not a character device
#define MAR_ERROR_DEVICE_OPEN 10
unable to open device
#define MAR_ERROR_NOT_V4L2_DEVICE 11
device is not a V4L2 device
#define MAR_ERROR_NOT_VIDEO_CAPTURE_DEVICE 12
device is not a capture device
#define MAR_ERROR_NOT_STREAMING_DEVICE 13
device is not a streaming device
#define MAR_ERROR_PIXEL_FORMAT_NOT_SUPPORTED 14
pixel format is not supported
#define MAR_ERROR_DEVICE_CLOSE 15
unable to close device
#define MAR_ERROR_NO_BUFFER_QUEUED 16
error queueing buffer
#define MAR_ERROR_NO_STREAM_ON 17
unable to turn stream on
#define MAR_ERROR_INTERRUPTED 18
interrupt occurred
#define MAR_ERROR_DEVICE_SELECT 19
error during select call
#define MAR_ERROR_CAMERA_TIMEOUT 20
timed out waiting for camera frame
#define MAR_ERROR_AGAIN 21
try again
#define MAR_ERROR_NO_BUFFER_DEQUEUED 22
error dequeueing buffer
#define MAR_ERROR_STREAM_NOT_OFF 24
error turning stream off
#define MAR_ERROR_CAM_TYPE_NOT_SUPPORTED 25
camera type is not supported
#define MAR_ERROR_NO_CAMERAS_AVAILABLE 26
no MAR camera resources available
#define MAR_ERROR_MSER_FILTER_NOT_CREATED 27
no MSER filter created
#define MAR_ERROR_SIFT_FILTER_NOT_CREATED 28
no SIFT filter created
#define MAR_NUMBER_OF_ERRORS 29
The number of error codes.
Typedefs
typedef unsigned char mar_error_code
An error code for the MAR library.
Functions
char * mar_error_get_string (mar_error_code error)
Returns a string describing an error code.
void mar_print_error (mar_error_code error)
Prints a string describing an error to standard error.
Detailed Description
Contains code which is used for error codes of the MAR library.
Author:
Greg Eddington
Typedef Documentation
typedef unsigned char mar_error_code
An error code for the MAR library.
Returns:
Function Documentation
char* mar_error_get_string (mar_error_code error)
Returns a string describing an error code.
Parameters:
error The error code.
Returns:
A string describing the error message.
References error_to_string_map.
Referenced by mar_print_error().
void mar_print_error (mar_error_code error)
Prints a string describing an error to standard error.
Parameters:
error The error code.
References mar_error_get_string().
Referenced by cleanup_lighthouse(), draw_mser_ellipses(), draw_region_preview(), draw_selectable_regions(), draw_sift_keypoints(), main(), and update_and_display().