MAR: mar_error.c File Reference
mar_error.c File Reference
Contains code which is used for error codes of the MAR library.
#include "mar_error.h"
#include "mar_common.h"
#include <stdio.h>
Functions
MAR_PUBLIC char * mar_error_get_string (mar_error_code error)
Returns a string describing an error code.
MAR_PUBLIC void mar_print_error (mar_error_code error)
Prints a string describing an error to standard error.
Variables
MAR_PRIVATE char * error_to_string_map [MAR_NUMBER_OF_ERRORS]
A mapping of error codes to strings describing them.
Detailed Description
Contains code which is used for error codes of the MAR library.
Author:
Greg Eddington
Function Documentation
MAR_PUBLIC char* mar_error_get_string (mar_error_code error)
Returns a string describing an error code.
Parameters:
error The error code.
Returns:
A string describing the error message.
References error_to_string_map.
Referenced by mar_print_error().
MAR_PUBLIC void mar_print_error (mar_error_code error)
Prints a string describing an error to standard error.
Parameters:
error The error code.
References mar_error_get_string().
Referenced by cleanup_lighthouse(), draw_mser_ellipses(), draw_region_preview(), draw_selectable_regions(), draw_sift_keypoints(), main(), and update_and_display().
Variable Documentation
MAR_PRIVATE char* error_to_string_map[MAR_NUMBER_OF_ERRORS]
A mapping of error codes to strings describing them.
Returns:
A string describing a given error code
Referenced by mar_error_get_string().