MAR: mar_v4l2_mmap_camera.c File Reference
mar_v4l2_mmap_camera.c File Reference
Contains camera interfacing code for the MAR library for cameras which are V4L2 compliant and are capable of memory mapping.
#include "mar_v4l2_mmap_camera.h"
#include "../common/mar_common.h"
#include "../common/mar_error.h"
#include <sys/mman.h>
#include <sys/stat.h>
#include <sys/ioctl.h>
#include <asm/types.h>
#include <linux/videodev2.h>
#include <fcntl.h>
#include <assert.h>
#include <stdlib.h>
#include <errno.h>
Functions
MAR_PRIVATE mar_error_code mar_v4l2_mmap_camera_mmap_init (mar_v4l2_mmap_camera *camera)
Initializes the camera to use memory mapping.
MAR_PRIVATE mar_error_code mar_v4l2_mmap_camera_mmap_free (mar_v4l2_mmap_camera *camera)
Frees camera memory mapped resources.
MAR_PUBLIC mar_error_code mar_v4l2_mmap_camera_new (mar_v4l2_mmap_camera **cam, char *dev_name, mar_camera_format format, int width, int height)
Initializes the camera portion of MAR.
MAR_PUBLIC mar_error_code mar_v4l2_mmap_camera_free (mar_v4l2_mmap_camera *camera)
Frees a camera created by the MAR library.
MAR_PUBLIC mar_error_code mar_v4l2_mmap_camera_start (mar_v4l2_mmap_camera *camera)
Starts camera capturing.
MAR_PRIVATE void mar_v4l2_mmap_camera_yuv_to_rgb (unsigned char y, unsigned char u, unsigned char v, unsigned char *r, unsigned char *g, unsigned char *b)
Converts a YUV color value to RGB.
MAR_PRIVATE void mar_v4l2_mmap_camera_yuyv_fill_frame (mar_v4l2_mmap_camera *camera, int mmap_buffer_index)
Updates the camera frame buffer from the camera's value buffer.
MAR_PUBLIC mar_error_code mar_v4l2_mmap_camera_update (mar_v4l2_mmap_camera *camera)
Updates the camera and captuers a new frame.
MAR_PUBLIC mar_error_code mar_v4l2_mmap_camera_stop (mar_v4l2_mmap_camera *camera)
Stops camera capturing.
MAR_PUBLIC mar_camera_format mar_v4l2_mmap_camera_get_pixel_format (mar_v4l2_mmap_camera *camera)
Returns the currently set camera pixel format.
MAR_PUBLIC void mar_v4l2_mmap_camera_get_resolution (mar_v4l2_mmap_camera *camera, int *width, int *height)
Returns the currently set camera resolution.
unsigned char * mar_v4l2_mmap_camera_get_frame_buffer (mar_v4l2_mmap_camera *camera)
Returns the camera's frame buffer in an RGB24 format.
Detailed Description
Contains camera interfacing code for the MAR library for cameras which are V4L2 compliant and are capable of memory mapping.
Author:
Greg Eddington
Function Documentation
MAR_PUBLIC mar_error_code mar_v4l2_mmap_camera_free (mar_v4l2_mmap_camera * camera)
Frees a camera created by the MAR library.
Parameters:
camera The camera to free
Returns:
MAR_ERROR_NONE on success, an error code on failure
References mar_v4l2_mmap_camera::dev_fd, mar_v4l2_mmap_camera::frame_buffer, and mar_v4l2_mmap_camera_mmap_free().
Referenced by mar_camera_free().
unsigned char* mar_v4l2_mmap_camera_get_frame_buffer (mar_v4l2_mmap_camera * camera)
Returns the camera's frame buffer in an RGB24 format.
The frame buffer is 3 * width * height in size.
Parameters:
camera The camera to get the frame buffer of.
Returns:
The camera buffer.
References mar_v4l2_mmap_camera::frame_buffer.
Referenced by mar_camera_get_frame_buffer().
MAR_PUBLIC mar_camera_format mar_v4l2_mmap_camera_get_pixel_format (mar_v4l2_mmap_camera * camera)
Returns the currently set camera pixel format.
Parameters:
camera The camera to get the pixel format from
Returns:
The camera pixel format.
References mar_v4l2_mmap_camera::format.
Referenced by mar_camera_get_pixel_format().
MAR_PUBLIC void mar_v4l2_mmap_camera_get_resolution (mar_v4l2_mmap_camera * camera, int * width, int * height)
Returns the currently set camera resolution.
Parameters:
camera The camera to get the resolution from
width Will be filled with the current resolution width.
height Will be filled with the current resolution height.
References mar_v4l2_mmap_camera::height, and mar_v4l2_mmap_camera::width.
Referenced by mar_camera_get_resolution().
MAR_PRIVATE mar_error_code mar_v4l2_mmap_camera_mmap_free (mar_v4l2_mmap_camera * camera)
Frees camera memory mapped resources.
Parameters:
camera The camera to free memory mapped resources from
Returns:
An MAR_ERROR_NONE on success, an error code on failure
References mar_v4l2_mmap_camera::mmap_buffer_length, mar_v4l2_mmap_camera::mmap_buffers, and mar_v4l2_mmap_camera::num_mmap_buffers.
Referenced by mar_v4l2_mmap_camera_free().
MAR_PRIVATE mar_error_code mar_v4l2_mmap_camera_mmap_init (mar_v4l2_mmap_camera * camera)
Initializes the camera to use memory mapping.
Parameters:
camera The camera to initialize
Returns:
An MAR_ERROR_NONE on success, an error code on failure
References mar_v4l2_mmap_camera::dev_fd, mar_block_ioctl(), MAR_CLEAR, mar_v4l2_mmap_camera::mmap_buffer_length, mar_v4l2_mmap_camera::mmap_buffers, and mar_v4l2_mmap_camera::num_mmap_buffers.
Referenced by mar_v4l2_mmap_camera_new().
MAR_PUBLIC mar_error_code mar_v4l2_mmap_camera_new (mar_v4l2_mmap_camera ** cam, char * dev_name, mar_camera_format format, int width, int height)
Initializes the camera portion of MAR.
Parameters:
cam A pointer to a pointer which will be modified to point at a new camera
dev_name The camera device
format The camera pixel format
width The camera resolution width
height The camera resolution height
Returns:
MAR_ERROR_NONE on success, an error code on failure
References mar_v4l2_mmap_camera::dev_fd, mar_v4l2_mmap_camera::format, mar_v4l2_mmap_camera::frame_buffer, mar_v4l2_mmap_camera::frame_buffer_length, mar_v4l2_mmap_camera::height, mar_block_ioctl(), MAR_CAM_FMT_YUYV, MAR_CLEAR, MAR_ERROR_NONE, mar_v4l2_mmap_camera_mmap_init(), and mar_v4l2_mmap_camera::width.
Referenced by mar_camera_new().
MAR_PUBLIC mar_error_code mar_v4l2_mmap_camera_start (mar_v4l2_mmap_camera * camera)
Starts camera capturing.
Parameters:
camera The camera
Returns:
MAR_ERROR_NONE on success, an error code on failure
References mar_v4l2_mmap_camera::dev_fd, mar_block_ioctl(), MAR_CLEAR, and mar_v4l2_mmap_camera::num_mmap_buffers.
Referenced by mar_camera_start().
MAR_PUBLIC mar_error_code mar_v4l2_mmap_camera_stop (mar_v4l2_mmap_camera * camera)
Stops camera capturing.
Parameters:
camera The camera
Returns:
MAR_ERROR_NONE on success, an error code on failure
References mar_v4l2_mmap_camera::dev_fd, and mar_block_ioctl().
Referenced by mar_camera_stop().
MAR_PUBLIC mar_error_code mar_v4l2_mmap_camera_update (mar_v4l2_mmap_camera * camera)
Updates the camera and captuers a new frame.
Parameters:
camera The camera to update
Returns:
MAR_ERROR_NONE on success, an error code on failure
References mar_v4l2_mmap_camera::dev_fd, mar_v4l2_mmap_camera::format, mar_block_ioctl(), MAR_CAM_FMT_YUYV, MAR_CLEAR, mar_v4l2_mmap_camera_yuyv_fill_frame(), and mar_v4l2_mmap_camera::num_mmap_buffers.
Referenced by mar_camera_update().
MAR_PRIVATE void mar_v4l2_mmap_camera_yuv_to_rgb (unsigned char y, unsigned char u, unsigned char v, unsigned char * r, unsigned char * g, unsigned char * b)
Converts a YUV color value to RGB.
Parameters:
y The Y color component
u The U color component
v The V color component
r The red color component
g The green color component
b The blue color component
Referenced by mar_v4l2_mmap_camera_yuyv_fill_frame().
MAR_PRIVATE void mar_v4l2_mmap_camera_yuyv_fill_frame (mar_v4l2_mmap_camera * camera, int mmap_buffer_index)
Updates the camera frame buffer from the camera's value buffer.
Parameters:
camera The camera
mmap_buffer_index The index of the current mmap buffer
References mar_v4l2_mmap_camera::frame_buffer, mar_v4l2_mmap_camera_yuv_to_rgb(), mar_v4l2_mmap_camera::mmap_buffer_length, and mar_v4l2_mmap_camera::mmap_buffers.
Referenced by mar_v4l2_mmap_camera_update().