MAR: mar_visualizer.c File Reference
mar_visualizer.c File Reference
Contains a visualization program which lets users visualize the steps of the MAR library.
#include "../camera/mar_camera.h"
#include "../common/mar_error.h"
#include <stdio.h>
#include <stdlib.h>
Functions
int main (int argc, char *argv[])
Entry point of the MAR visualization application.
Detailed Description
Contains a visualization program which lets users visualize the steps of the MAR library.
It is designed specifically for development, testing, and calibration.
Author:
Greg Eddington
Function Documentation
int main (int argc, char * argv[])
Entry point of the MAR visualization application.
Parameters:
argc The number of arguments
argv The arguments
Returns:
EXIT_SUCCESS on success, EXIT_FAILURE otherwise
References mar_camera::frame_buffer, mar_camera::frame_buffer_length, MAR_CAM_FMT_YUYV, mar_camera_free(), mar_camera_new(), mar_camera_start(), mar_camera_stop(), mar_camera_update(), MAR_ERROR_AGAIN, MAR_ERROR_INTERRUPTED, MAR_ERROR_NONE, and mar_print_error().