MAR: mar_mser.c File Reference
mar_mser.c File Reference
Contains code which is used for the maximally stable extremal region algorithm.
#include "../common/mar_error.h"
#include "../common/mar_common.h"
#include "mar_mser.h"
#include <mser.h>
#include <stdio.h>
#include <math.h>
Functions
MAR_PUBLIC mar_error_code mar_mser_new (int width, int height)
Creates a new MSER filter.
MAR_PUBLIC void mar_mser_free ()
Frees the MSER filter created by mar_mser_new.
MAR_PUBLIC mar_error_code mar_mser_set_delta (float delta)
Sets the delta value for MSER filter.
MAR_PUBLIC mar_error_code mar_mser_set_min_area (float min_area)
Sets the minimum area for MSER filter regions.
MAR_PUBLIC mar_error_code mar_mser_set_max_area (float max_area)
Sets the maximum area for MSER filter regions.
MAR_PUBLIC mar_error_code mar_mser_set_max_variation (float max_variation)
Sets the max variation value for MSER filter.
MAR_PUBLIC mar_error_code mar_mser_set_min_diversity (float min_diversity)
Sets the minimum diversity value for MSER filter.
MAR_PUBLIC mar_error_code mar_mser_get_delta (float *delta)
Gets the delta value for MSER filter.
MAR_PUBLIC mar_error_code mar_mser_get_min_area (float *min_area)
Gets the minimum area for MSER filter regions.
MAR_PUBLIC mar_error_code mar_mser_get_max_area (float *max_area)
Gets the maximum area for MSER filter regions.
MAR_PUBLIC mar_error_code mar_mser_get_max_variation (float *max_variation)
Gets the max variation value for MSER filter.
MAR_PUBLIC mar_error_code mar_mser_get_min_diversity (float *min_diversity)
Gets the minimum diversity value for MSER filter.
MAR_PUBLIC mar_error_code mar_mser_get_regions (mar_mser **regions, int *num_regions, unsigned char *frame_buffer)
Calculates and returns the maximally stable extremal regions for a camera frame.
Variables
MAR_PRIVATE VlMserFilt * mser_filter = NULL
The MSER filter.
MAR_PRIVATE unsigned char * mser_image_buffer
The image buffer to store a grayscale of the camera image for MSER filtering.
MAR_PRIVATE int mser_image_width = 0
The image buffer width.
MAR_PRIVATE int mser_image_height = 0
The image buffer height.
MAR_PRIVATE mar_mser * mser_regions = NULL
A buffer for holding MSER ellipses found from filtering.
MAR_PRIVATE int mser_regions_size = MAR_MSER_DEFAULT_NUMBER_OF_REGIONS
The size of the MSER region buffer.
Detailed Description
Contains code which is used for the maximally stable extremal region algorithm.
Author:
Greg Eddington
Function Documentation
MAR_PUBLIC void mar_mser_free ()
Frees the MSER filter created by mar_mser_new.
References mser_filter, mser_image_buffer, and mser_regions.
Referenced by mar_augment_free(), and mar_augment_init().
MAR_PUBLIC mar_error_code mar_mser_get_delta (float * delta)
Gets the delta value for MSER filter.
May only be called if a MSER filter has been created.
Parameters:
delta Will be filled with the filter delta
Returns:
MAR_ERROR_NONE on success, an error code on failure.
References mser_filter.
Referenced by keyboard().
MAR_PUBLIC mar_error_code mar_mser_get_max_area (float * max_area)
Gets the maximum area for MSER filter regions.
May only be called if a MSER filter has been created.
Parameters:
max_area Will be filled with the maximum region area, normalized to [0-1], where one is the total area of the image.
Returns:
MAR_ERROR_NONE on success, an error code on failure.
References mser_filter.
Referenced by keyboard().
MAR_PUBLIC mar_error_code mar_mser_get_max_variation (float * max_variation)
Gets the max variation value for MSER filter.
May only be called if a MSER filter has been created.
Parameters:
max_variation Will be filled with the filter's max variation
Returns:
MAR_ERROR_NONE on success, an error code on failure.
References mser_filter.
Referenced by keyboard().
MAR_PUBLIC mar_error_code mar_mser_get_min_area (float * min_area)
Gets the minimum area for MSER filter regions.
May only be called if a MSER filter has been created.
Parameters:
min_area Will be filled with the minimum region area, normalized to [0-1], where one is the total area of the image.
Returns:
MAR_ERROR_NONE on success, an error code on failure.
References mser_filter.
Referenced by keyboard().
MAR_PUBLIC mar_error_code mar_mser_get_min_diversity (float * min_diversity)
Gets the minimum diversity value for MSER filter.
May only be called if a MSER filter has been created.
Parameters:
min_diversity The filter minimum diversity
Returns:
MAR_ERROR_NONE on success, an error code on failure.
References mser_filter.
Referenced by keyboard().
MAR_PUBLIC mar_error_code mar_mser_get_regions (mar_mser ** regions, int * num_regions, unsigned char * frame_buffer)
Calculates and returns the maximally stable extremal regions for a camera frame.
Parameters:
regions A pointer to a pointer which will be modified to point to the array of regions.
num_regions The number of MSER, and the size of the regions array
frame_buffer The camera's frame buffer
Returns:
MAR_ERROR_NONE on success, an error code on failure.
References mar_mser::ellipse_a, mar_mser::ellipse_angle, mar_mser::ellipse_b, mar_mser::ellipse_x, mar_mser::ellipse_y, mser_filter, mser_image_buffer, mser_image_height, mser_image_width, mser_regions, and mser_regions_size.
Referenced by mar_augment_get_regions().
MAR_PUBLIC mar_error_code mar_mser_new (int width, int height)
Creates a new MSER filter.
Must be called before calling other MAR MSER functions.
Parameters:
width The width of the camera frame
height The height of the camera frame
Returns:
MAR_ERROR_NONE on success, an error code on failure.
References MAR_MSER_DEFAULT_NUMBER_OF_REGIONS, mser_filter, mser_image_buffer, mser_image_height, mser_image_width, and mser_regions.
Referenced by mar_augment_init().
MAR_PUBLIC mar_error_code mar_mser_set_delta (float delta)
Sets the delta value for MSER filter.
May only be called if a MSER filter has been created.
Parameters:
delta The filter delta
Returns:
MAR_ERROR_NONE on success, an error code on failure.
References mser_filter.
Referenced by keyboard(), and mar_augment_init().
MAR_PUBLIC mar_error_code mar_mser_set_max_area (float max_area)
Sets the maximum area for MSER filter regions.
May only be called if a MSER filter has been created.
Parameters:
max_area The maximum region area, normalized to [0-1], where one is the total area of the image.
Returns:
MAR_ERROR_NONE on success, an error code on failure.
References mser_filter.
Referenced by keyboard(), and mar_augment_init().
MAR_PUBLIC mar_error_code mar_mser_set_max_variation (float max_variation)
Sets the max variation value for MSER filter.
May only be called if a MSER filter has been created.
Parameters:
max_variation The filter max variation
Returns:
MAR_ERROR_NONE on success, an error code on failure.
References mser_filter.
Referenced by keyboard(), and mar_augment_init().
MAR_PUBLIC mar_error_code mar_mser_set_min_area (float min_area)
Sets the minimum area for MSER filter regions.
May only be called if a MSER filter has been created.
Parameters:
min_area The minimum region area, normalized to [0-1], where one is the total area of the image.
Returns:
MAR_ERROR_NONE on success, an error code on failure.
References mser_filter.
Referenced by keyboard(), and mar_augment_init().
MAR_PUBLIC mar_error_code mar_mser_set_min_diversity (float min_diversity)
Sets the minimum diversity value for MSER filter.
May only be called if a MSER filter has been created.
Parameters:
min_diversity The filter minimum diversity
Returns:
MAR_ERROR_NONE on success, an error code on failure.
References mser_filter.
Referenced by keyboard(), and mar_augment_init().
Variable Documentation
MAR_PRIVATE VlMserFilt* mser_filter = NULL
The MSER filter.
Returns:
Referenced by mar_mser_free(), mar_mser_get_delta(), mar_mser_get_max_area(), mar_mser_get_max_variation(), mar_mser_get_min_area(), mar_mser_get_min_diversity(), mar_mser_get_regions(), mar_mser_new(), mar_mser_set_delta(), mar_mser_set_max_area(), mar_mser_set_max_variation(), mar_mser_set_min_area(), and mar_mser_set_min_diversity().
MAR_PRIVATE unsigned char* mser_image_buffer
The image buffer to store a grayscale of the camera image for MSER filtering.
Returns:
Referenced by mar_mser_free(), mar_mser_get_regions(), and mar_mser_new().
MAR_PRIVATE int mser_image_height = 0
The image buffer height.
Returns:
Referenced by mar_mser_get_regions(), and mar_mser_new().
MAR_PRIVATE int mser_image_width = 0
The image buffer width.
Returns:
Referenced by mar_mser_get_regions(), and mar_mser_new().
MAR_PRIVATE mar_mser* mser_regions = NULL
A buffer for holding MSER ellipses found from filtering.
Returns:
Referenced by mar_mser_free(), mar_mser_get_regions(), and mar_mser_new().
MAR_PRIVATE int mser_regions_size = MAR_MSER_DEFAULT_NUMBER_OF_REGIONS
The size of the MSER region buffer.
Returns:
Referenced by mar_mser_get_regions().