MAR: mar_camera.c File Reference
mar_camera.c File Reference
Contains camera interfacing code for the MAR library.
#include "mar_camera.h"
#include "../common/mar_common.h"
#include "mar_v4l2_mmap_camera.h"
Data Structures
struct mar_camera
Contains information for MAR library camera instances.
Functions
mar_error_code mar_camera_new (mar_camera_id *id, mar_camera_type type, char *dev_name, mar_camera_format format, int width, int height)
Initializes a MAR camera.
mar_error_code mar_camera_free (mar_camera_id id)
Frees a camera created by the MAR library.
mar_error_code mar_camera_start (mar_camera_id id)
Starts camera capturing.
mar_error_code mar_camera_update (mar_camera_id id)
Updates the camera and captuers a new frame.
mar_error_code mar_camera_stop (mar_camera_id id)
Stops camera capturing.
mar_camera_format mar_camera_get_pixel_format (mar_camera_id id)
Returns the currently set camera pixel format.
void mar_camera_get_resolution (mar_camera_id id, int *width, int *height)
Returns the currently set camera resolution.
unsigned char * mar_camera_get_frame_buffer (mar_camera_id id)
Returns the camera's frame buffer in an RGB24 format.
Variables
MAR_PRIVATE mar_camera mar_cameras [MAR_CAM_MAX_NUM_CAMERAS] = { { 0 } }
Detailed Description
Contains camera interfacing code for the MAR library.
Author:
Greg Eddington
Function Documentation
mar_error_code mar_camera_free (mar_camera_id id)
Frees a camera created by the MAR library.
Parameters:
id The ID of the camera to free
Returns:
MAR_ERROR_NONE on success, an error code on failure
References mar_camera::camera, MAR_CAM_TYPE_V4L2_MMAP, and mar_v4l2_mmap_camera_free().
Referenced by mar_augment_free(), and mar_augment_init().
unsigned char* mar_camera_get_frame_buffer (mar_camera_id id)
Returns the camera's frame buffer in an RGB24 format.
The frame buffer is 3 * width * height in size.
Parameters:
id The ID of the camera to get the frame buffer of.
Returns:
The camera frame buffer.
References MAR_CAM_TYPE_V4L2_MMAP, and mar_v4l2_mmap_camera_get_frame_buffer().
Referenced by mar_augment_get_camera_frame_buffer(), mar_augment_get_keypoints(), mar_augment_get_regions(), and mar_augment_update().
mar_camera_format mar_camera_get_pixel_format (mar_camera_id id)
Returns the currently set camera pixel format.
Parameters:
id The ID of the camera to get the pixel format from
Returns:
The camera pixel format.
References MAR_CAM_TYPE_V4L2_MMAP, and mar_v4l2_mmap_camera_get_pixel_format().
void mar_camera_get_resolution (mar_camera_id id, int * width, int * height)
Returns the currently set camera resolution.
Parameters:
id The ID of the camera to get the resolution from
width Will be filled with the current resolution width.
height Will be filled with the current resolution height.
References MAR_CAM_TYPE_V4L2_MMAP, and mar_v4l2_mmap_camera_get_resolution().
mar_error_code mar_camera_new (mar_camera_id * id, mar_camera_type type, char * dev_name, mar_camera_format format, int width, int height)
Initializes a MAR camera.
Parameters:
id A pointer to an int which will be filled with the ID of the newly created camera
type The type of camera to create
dev_name The camera device name
format The camera pixel format
width The camera resolution width
height The camera resolution height
Returns:
MAR_ERROR_NONE on success, an error code on failure.
References mar_camera::camera, MAR_CAM_MAX_NUM_CAMERAS, MAR_CAM_TYPE_V4L2_MMAP, MAR_ERROR_NONE, mar_v4l2_mmap_camera_new(), and mar_camera::type.
Referenced by mar_augment_init().
mar_error_code mar_camera_start (mar_camera_id id)
Starts camera capturing.
Parameters:
id The ID of the camera
Returns:
MAR_ERROR_NONE on success, an error code on failure
References MAR_CAM_TYPE_V4L2_MMAP, and mar_v4l2_mmap_camera_start().
Referenced by mar_augment_start().
mar_error_code mar_camera_stop (mar_camera_id id)
Stops camera capturing.
Parameters:
id The ID of the camera
Returns:
MAR_ERROR_NONE on success, an error code on failure
References MAR_CAM_TYPE_V4L2_MMAP, and mar_v4l2_mmap_camera_stop().
Referenced by mar_augment_stop().
mar_error_code mar_camera_update (mar_camera_id id)
Updates the camera and captuers a new frame.
Parameters:
id The ID of the camera it update
Returns:
MAR_ERROR_NONE on success, an error code on failure
References MAR_CAM_TYPE_V4L2_MMAP, and mar_v4l2_mmap_camera_update().
Referenced by mar_augment_update().
Variable Documentation
MAR_PRIVATE mar_camera mar_cameras[MAR_CAM_MAX_NUM_CAMERAS] = { { 0 } }
Returns:
An array of cameras instantiated by the MAR library.