MAR: mar_augment.h File Reference
mar_augment.h File Reference
Contains code which is used for augmentation.
#include "../common/mar_error.h"
#include "../camera/mar_camera.h"
#include "../vision/mar_mser.h"
#include "../vision/mar_sift.h"
Defines
#define MAR_MAX_NUMBER_OF_AUGMENTATIONS 32
The maximum number of augmentations.
Typedefs
typedef unsigned char mar_augmentation_id
An augmentation identifier.
Functions
mar_error_code mar_augment_init (char *filename)
Initializes augmentation using a configuration file.
mar_error_code mar_augment_init_from_defaults ()
Initializes augmentation using default settings.
mar_error_code mar_augment_start ()
Starts the augmentation camera.
mar_error_code mar_augment_stop ()
Stops the augmentation camera.
mar_error_code mar_augment_update ()
Updates an augmentation frame.
mar_camera_id mar_augment_get_camera ()
Gets the camera ID used for augmentation.
mar_error_code mar_augment_get_regions (mar_mser **regions, int *num_regions)
Returns the maximally stable extremal regions for a camera frame.
mar_error_code mar_augment_get_keypoints (mar_sift_keypoint **keypoints, int *num_keypoints)
Returns the SIFT keypoints for a camera frame.
unsigned char * mar_augment_get_camera_frame_buffer ()
Returns the camera's frame buffer in an RGB24 format.
mar_error_code mar_augment_free ()
Frees the augmentation resources.
Detailed Description
Contains code which is used for augmentation.
Author:
Greg Eddington
Define Documentation
#define MAR_MAX_NUMBER_OF_AUGMENTATIONS 32
The maximum number of augmentations.
Typedef Documentation
typedef unsigned char mar_augmentation_id
An augmentation identifier.
Function Documentation
mar_error_code mar_augment_free ()
Frees the augmentation resources.
Returns:
MAR_ERROR_NONE on success, an error code on failure.
References camera_id, mar_augment_initialized, mar_camera_free(), mar_cfg, mar_mser_free(), and mar_sift_free().
Referenced by cleanup_lighthouse().
mar_camera_id mar_augment_get_camera ()
Gets the camera ID used for augmentation.
Returns:
The MAR library camera ID for the camera being used for augmentation
References camera_id.
unsigned char* mar_augment_get_camera_frame_buffer ()
Returns the camera's frame buffer in an RGB24 format.
The frame buffer is 3 * width * height in size.
Returns:
The camera frame buffer.
References camera_id, and mar_camera_get_frame_buffer().
Referenced by draw_camera_frame().
mar_error_code mar_augment_get_keypoints (mar_sift_keypoint ** keypoints, int * num_keypoints)
Returns the SIFT keypoints for a camera frame.
Parameters:
keypoints A pointer to a pointer which will be modified to point to the array of keypoints.
num_keypoints The number of SIFT keypoints, and the size of the regions array
Returns:
MAR_ERROR_NONE on success, an error code on failure.
References camera_id, mar_camera_get_frame_buffer(), mar_sift_calculated_this_frame, mar_sift_get_keypoints(), mar_sift_keypoints, and mar_sift_num_keypoints.
Referenced by draw_sift_keypoints().
mar_error_code mar_augment_get_regions (mar_mser ** regions, int * num_regions)
Returns the maximally stable extremal regions for a camera frame.
Parameters:
regions A pointer to a pointer which will be modified to point to the array of regions.
num_regions The number of MSER, and the size of the regions array
Returns:
MAR_ERROR_NONE on success, an error code on failure.
References camera_id, mar_camera_get_frame_buffer(), mar_mser_calculated_this_frame, mar_mser_get_regions(), mar_mser_num_regions, and mar_mser_regions.
Referenced by draw_mser_ellipses(), draw_region_preview(), and draw_selectable_regions().
mar_error_code mar_augment_init (char * filename)
Initializes augmentation using a configuration file.
Parameters:
filename The filename of the configuration file, NULL for default settings
Returns:
MAR_ERROR_NONE on success, an error code on failure.
Todo:
throw errors if initialized
Todo:
throw errors at uninitialized
References camera_id, mar_augment_initialized, mar_camera_free(), mar_camera_new(), mar_cfg, MAR_ERROR_NONE, mar_mser_free(), mar_mser_new(), mar_mser_set_delta(), mar_mser_set_max_area(), mar_mser_set_max_variation(), mar_mser_set_min_area(), mar_mser_set_min_diversity(), mar_sift_new(), mar_sift_set_edge_threshold(), and mar_sift_set_peak_threshold().
Referenced by main(), and mar_augment_init_from_defaults().
mar_error_code mar_augment_init_from_defaults ()
Initializes augmentation using default settings.
Returns:
MAR_ERROR_NONE on success, an error code on failure.
References mar_augment_init().
mar_error_code mar_augment_start ()
Starts the augmentation camera.
Returns:
MAR_ERROR_NONE on success, an error code on failure.
References camera_id, and mar_camera_start().
Referenced by main().
mar_error_code mar_augment_stop ()
Stops the augmentation camera.
Returns:
MAR_ERROR_NONE on success, an error code on failure.
References camera_id, and mar_camera_stop().
mar_error_code mar_augment_update ()
Updates an augmentation frame.
Returns:
MAR_ERROR_NONE on success, an error code on failure.
Todo:
augment reality
Todo:
check retval
References camera_id, mar_camera_get_frame_buffer(), mar_camera_update(), MAR_ERROR_NONE, mar_mser_calculated_this_frame, mar_number_of_augmentations, mar_sift_calculated_this_frame, mar_sift_get_keypoints(), mar_sift_keypoints, and mar_sift_num_keypoints.
Referenced by update_and_display().