MAR: mar_common.h File Reference
mar_common.h File Reference
Contains code common across various components of the MAR library.
#include <string.h>
Defines
#define MAR_CLEAR(x) memset (&(x), 0, sizeof (x))
Sets a variable or all fields of a structure to zero.
#define MAR_PRIVATE static
A function private to a file.
#define MAR_PUBLIC
A public function.
Functions
int mar_block_ioctl (int fd, int request, void *arg)
Blocks until the ioctl function finishes.
Detailed Description
Contains code common across various components of the MAR library.
Author:
Greg Eddington
Define Documentation
#define MAR_CLEAR (x) memset (&(x), 0, sizeof (x))
Sets a variable or all fields of a structure to zero.
Referenced by mar_v4l2_mmap_camera_mmap_init(), mar_v4l2_mmap_camera_new(), mar_v4l2_mmap_camera_start(), and mar_v4l2_mmap_camera_update().
Function Documentation
int mar_block_ioctl (int fd, int request, void * arg)
Blocks until the ioctl function finishes.
Parameters:
fd The file descriptor
request The control request
arg The request argument
Returns:
The returned value of the ioctl call
Referenced by mar_v4l2_mmap_camera_mmap_init(), mar_v4l2_mmap_camera_new(), mar_v4l2_mmap_camera_start(), mar_v4l2_mmap_camera_stop(), and mar_v4l2_mmap_camera_update().