MAR: mar_camera.h File Reference
mar_camera.h File Reference
Contains camera interfacing code for the MAR library.
#include "../common/mar_error.h"
#include "../common/mar_error.h"
Defines
#define MAR_CAM_DEFAULT_TYPE MAR_CAM_TYPE_V4L2_MMAP
The default camera type.
#define MAR_CAM_DEFAULT_FORMAT MAR_CAM_FMT_YUYV
The default camera pixel format.
#define MAR_CAM_DEFAULT_WIDTH 320
The default camera width.
#define MAR_CAM_DEFAULT_HEIGHT 240
The default camera height.
#define MAR_CAM_DEFAULT_DEV_NAME "/dev/video0"
The default camera device name.
#define MAR_CAM_MAX_NUM_CAMERAS 2
The maximum number of cameras.
#define MAR_CAM_NO_CAMERA 255
A constant which can be used to initialize camera IDs to specify no camera.
#define MAR_CAM_TYPE_V4L2_MMAP 1
V4L2 Memory Mapped Devices.
#define MAR_CAM_FMT_YUYV 0x01
YUYV/YUY2 FourCC Pixel Format.
Typedefs
typedef unsigned char mar_camera_format
The camera pixel format.
typedef unsigned char mar_camera_type
The camera type.
typedef unsigned char mar_camera_id
A camera identifier.
Functions
mar_error_code mar_camera_new (mar_camera_id *id, mar_camera_type type, char *dev_name, mar_camera_format format, int width, int height)
Initializes a MAR camera.
mar_error_code mar_camera_free (mar_camera_id id)
Frees a camera created by the MAR library.
mar_error_code mar_camera_start (mar_camera_id id)
Starts camera capturing.
mar_error_code mar_camera_update (mar_camera_id id)
Updates the camera and captuers a new frame.
mar_error_code mar_camera_stop (mar_camera_id id)
Stops camera capturing.
mar_camera_format mar_camera_get_pixel_format (mar_camera_id id)
Returns the currently set camera pixel format.
void mar_camera_get_resolution (mar_camera_id id, int *width, int *height)
Returns the currently set camera resolution.
unsigned char * mar_camera_get_frame_buffer (mar_camera_id id)
Returns the camera's frame buffer in an RGB24 format.
Detailed Description
Contains camera interfacing code for the MAR library.
Author:
Greg Eddington
Define Documentation
#define MAR_CAM_DEFAULT_DEV_NAME "/dev/video0"
The default camera device name.
#define MAR_CAM_DEFAULT_FORMAT MAR_CAM_FMT_YUYV
The default camera pixel format.
#define MAR_CAM_DEFAULT_HEIGHT 240
The default camera height.
#define MAR_CAM_DEFAULT_TYPE MAR_CAM_TYPE_V4L2_MMAP
The default camera type.
#define MAR_CAM_DEFAULT_WIDTH 320
The default camera width.
#define MAR_CAM_MAX_NUM_CAMERAS 2
The maximum number of cameras.
Referenced by mar_camera_new().
#define MAR_CAM_NO_CAMERA 255
A constant which can be used to initialize camera IDs to specify no camera.
Typedef Documentation
typedef unsigned char mar_camera_format
The camera pixel format.
Returns:
typedef unsigned char mar_camera_id
A camera identifier.
Returns:
typedef unsigned char mar_camera_type
The camera type.
Returns:
Function Documentation
mar_error_code mar_camera_free (mar_camera_id id)
Frees a camera created by the MAR library.
Parameters:
id The ID of the camera to free
Returns:
MAR_ERROR_NONE on success, an error code on failure
References mar_camera::camera, MAR_CAM_TYPE_V4L2_MMAP, and mar_v4l2_mmap_camera_free().
Referenced by mar_augment_free(), and mar_augment_init().
unsigned char* mar_camera_get_frame_buffer (mar_camera_id id)
Returns the camera's frame buffer in an RGB24 format.
The frame buffer is 3 * width * height in size.
Parameters:
id The ID of the camera to get the frame buffer of.
Returns:
The camera frame buffer.
References MAR_CAM_TYPE_V4L2_MMAP, and mar_v4l2_mmap_camera_get_frame_buffer().
Referenced by mar_augment_get_camera_frame_buffer(), mar_augment_get_keypoints(), mar_augment_get_regions(), and mar_augment_update().
mar_camera_format mar_camera_get_pixel_format (mar_camera_id id)
Returns the currently set camera pixel format.
Parameters:
id The ID of the camera to get the pixel format from
Returns:
The camera pixel format.
References MAR_CAM_TYPE_V4L2_MMAP, and mar_v4l2_mmap_camera_get_pixel_format().
void mar_camera_get_resolution (mar_camera_id id, int * width, int * height)
Returns the currently set camera resolution.
Parameters:
id The ID of the camera to get the resolution from
width Will be filled with the current resolution width.
height Will be filled with the current resolution height.
References MAR_CAM_TYPE_V4L2_MMAP, and mar_v4l2_mmap_camera_get_resolution().
mar_error_code mar_camera_new (mar_camera_id * id, mar_camera_type type, char * dev_name, mar_camera_format format, int width, int height)
Initializes a MAR camera.
Parameters:
id A pointer to an int which will be filled with the ID of the newly created camera
type The type of camera to create
dev_name The camera device name
format The camera pixel format
width The camera resolution width
height The camera resolution height
Returns:
MAR_ERROR_NONE on success, an error code on failure
Parameters:
id A pointer to an int which will be filled with the ID of the newly created camera
type The type of camera to create
dev_name The camera device name
format The camera pixel format
width The camera resolution width
height The camera resolution height
Returns:
MAR_ERROR_NONE on success, an error code on failure.
References mar_camera::camera, MAR_CAM_MAX_NUM_CAMERAS, MAR_CAM_TYPE_V4L2_MMAP, MAR_ERROR_NONE, mar_v4l2_mmap_camera_new(), and mar_camera::type.
Referenced by mar_augment_init().
mar_error_code mar_camera_start (mar_camera_id id)
Starts camera capturing.
Parameters:
id The ID of the camera
Returns:
MAR_ERROR_NONE on success, an error code on failure
References MAR_CAM_TYPE_V4L2_MMAP, and mar_v4l2_mmap_camera_start().
Referenced by mar_augment_start().
mar_error_code mar_camera_stop (mar_camera_id id)
Stops camera capturing.
Parameters:
id The ID of the camera
Returns:
MAR_ERROR_NONE on success, an error code on failure
References MAR_CAM_TYPE_V4L2_MMAP, and mar_v4l2_mmap_camera_stop().
Referenced by mar_augment_stop().
mar_error_code mar_camera_update (mar_camera_id id)
Updates the camera and captuers a new frame.
Parameters:
id The ID of the camera it update
Returns:
MAR_ERROR_NONE on success, an error code on failure
References MAR_CAM_TYPE_V4L2_MMAP, and mar_v4l2_mmap_camera_update().
Referenced by mar_augment_update().