MAR: mar_v4l2_mmap_camera.h File Reference
mar_v4l2_mmap_camera.h File Reference
Contains camera interfacing code for the MAR library for cameras which are V4L2 compliant and are capable of memory mapping.
#include "../common/mar_error.h"
#include "mar_camera.h"
#include <unistd.h>
#include <stdint.h>
Data Structures
struct mar_v4l2_mmap_camera
A MAR camera instance for memory mapped V4L2 devices.
Defines
#define MAR_V4L2_MMAP_CAMERA_MAX_MMAP_BUFFER_NUMBER 4
The maximum number of camera mmap buffers.
Functions
mar_error_code mar_v4l2_mmap_camera_new (mar_v4l2_mmap_camera **cam, char *dev_name, mar_camera_format format, int width, int height)
Initializes the camera portion of MAR.
mar_error_code mar_v4l2_mmap_camera_free (mar_v4l2_mmap_camera *camera)
Frees a camera created by the MAR library.
mar_error_code mar_v4l2_mmap_camera_start (mar_v4l2_mmap_camera *camera)
Starts camera capturing.
mar_error_code mar_v4l2_mmap_camera_update (mar_v4l2_mmap_camera *camera)
Updates the camera and captuers a new frame.
mar_error_code mar_v4l2_mmap_camera_stop (mar_v4l2_mmap_camera *camera)
Stops camera capturing.
mar_camera_format mar_v4l2_mmap_camera_get_pixel_format (mar_v4l2_mmap_camera *camera)
Returns the currently set camera pixel format.
void mar_v4l2_mmap_camera_get_resolution (mar_v4l2_mmap_camera *camera, int *width, int *height)
Returns the currently set camera resolution.
unsigned char * mar_v4l2_mmap_camera_get_frame_buffer (mar_v4l2_mmap_camera *camera)
Returns the camera's frame buffer in an RGB24 format.
Detailed Description
Contains camera interfacing code for the MAR library for cameras which are V4L2 compliant and are capable of memory mapping.
Author:
Greg Eddington
Define Documentation
#define MAR_V4L2_MMAP_CAMERA_MAX_MMAP_BUFFER_NUMBER 4
The maximum number of camera mmap buffers.
Function Documentation
mar_error_code mar_v4l2_mmap_camera_free (mar_v4l2_mmap_camera * camera)
Frees a camera created by the MAR library.
Parameters:
camera The camera to free
Returns:
MAR_ERROR_NONE on success, an error code on failure
References mar_v4l2_mmap_camera::dev_fd, mar_v4l2_mmap_camera::frame_buffer, and mar_v4l2_mmap_camera_mmap_free().
Referenced by mar_camera_free().
unsigned char* mar_v4l2_mmap_camera_get_frame_buffer (mar_v4l2_mmap_camera * camera)
Returns the camera's frame buffer in an RGB24 format.
The frame buffer is 3 * width * height in size.
Parameters:
camera The camera to get the frame buffer of.
Returns:
The camera buffer.
References mar_v4l2_mmap_camera::frame_buffer.
Referenced by mar_camera_get_frame_buffer().
mar_camera_format mar_v4l2_mmap_camera_get_pixel_format (mar_v4l2_mmap_camera * camera)
Returns the currently set camera pixel format.
Parameters:
camera The camera to get the pixel format from
Returns:
The camera pixel format.
References mar_v4l2_mmap_camera::format.
Referenced by mar_camera_get_pixel_format().
void mar_v4l2_mmap_camera_get_resolution (mar_v4l2_mmap_camera * camera, int * width, int * height)
Returns the currently set camera resolution.
Parameters:
camera The camera to get the resolution from
width Will be filled with the current resolution width.
height Will be filled with the current resolution height.
References mar_v4l2_mmap_camera::height, and mar_v4l2_mmap_camera::width.
Referenced by mar_camera_get_resolution().
mar_error_code mar_v4l2_mmap_camera_new (mar_v4l2_mmap_camera ** cam, char * dev_name, mar_camera_format format, int width, int height)
Initializes the camera portion of MAR.
Parameters:
cam A pointer to a pointer which will be modified to point at a new camera
dev_name The camera device
format The camera pixel format
width The camera resolution width
height The camera resolution height
Returns:
MAR_ERROR_NONE on success, an error code on failure
References mar_v4l2_mmap_camera::dev_fd, mar_v4l2_mmap_camera::format, mar_v4l2_mmap_camera::frame_buffer, mar_v4l2_mmap_camera::frame_buffer_length, mar_v4l2_mmap_camera::height, mar_block_ioctl(), MAR_CAM_FMT_YUYV, MAR_CLEAR, MAR_ERROR_NONE, mar_v4l2_mmap_camera_mmap_init(), and mar_v4l2_mmap_camera::width.
Referenced by mar_camera_new().
mar_error_code mar_v4l2_mmap_camera_start (mar_v4l2_mmap_camera * camera)
Starts camera capturing.
Parameters:
camera The camera
Returns:
MAR_ERROR_NONE on success, an error code on failure
References mar_v4l2_mmap_camera::dev_fd, mar_block_ioctl(), MAR_CLEAR, and mar_v4l2_mmap_camera::num_mmap_buffers.
Referenced by mar_camera_start().
mar_error_code mar_v4l2_mmap_camera_stop (mar_v4l2_mmap_camera * camera)
Stops camera capturing.
Parameters:
camera The camera
Returns:
MAR_ERROR_NONE on success, an error code on failure
References mar_v4l2_mmap_camera::dev_fd, and mar_block_ioctl().
Referenced by mar_camera_stop().
mar_error_code mar_v4l2_mmap_camera_update (mar_v4l2_mmap_camera * camera)
Updates the camera and captuers a new frame.
Parameters:
camera The camera to update
Returns:
MAR_ERROR_NONE on success, an error code on failure
References mar_v4l2_mmap_camera::dev_fd, mar_v4l2_mmap_camera::format, mar_block_ioctl(), MAR_CAM_FMT_YUYV, MAR_CLEAR, mar_v4l2_mmap_camera_yuyv_fill_frame(), and mar_v4l2_mmap_camera::num_mmap_buffers.
Referenced by mar_camera_update().